[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
authors = ["Ben Gosney <bengosney@googlemail.com>"]

[dependencies]
cached = "0.54.0"
itertools = "0.13.0"
regex = "1.11.1"

[profile.release]
debug = true

[dev-dependencies]
bacon = "3.5.0"
